name: Publish

on:
  workflow_dispatch:

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/tooka-cli/
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
          installer-parallel: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      - name: Install project
        run: poetry install --no-interaction

      - name: Package project
        run: poetry build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: poetry-artifacts
          path: |
            dist/tooka-*.tar.gz
            dist/tooka-*.whl

#      - name: Publish package distributions to PyPI
#        uses: pypa/gh-action-pypi-publish@release/v1

  # Upload to GitHub release job
  upload_to_release:
    name: Upload files to release
    permissions: write-all
    runs-on: ubuntu-latest
    needs: [pypi-publish]
    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Create attestation for all builds
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: |
            artifacts/tooka-*.tar.gz
            artifacts/tooka-*.whl

      - name: Release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
          tag_name: Tooka vX.X
          files: |
            artifacts/tooka-*.tar.gz
            artifacts/tooka-*.whl