name: Test Go Code

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install dependencies
        run: go get .
      - name: Test with Go
        run: go test -json > TestResults.json
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results
          path: TestResults.json
